// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: event_ingestion.proto

package rpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_event_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_event_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *EventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_event_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_event_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_event_ingestion_proto protoreflect.FileDescriptor

const file_event_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x15event_ingestion.proto\x12\n" +
	"rpc_server\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\fEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"(\n" +
	"\x0eIngestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2U\n" +
	"\x0eEventIngestion\x12C\n" +
	"\vCreateEvent\x12\x18.rpc_server.EventRequest\x1a\x1a.rpc_server.IngestResponseB\fZ\n" +
	"rpcserver/b\x06proto3"

var (
	file_event_ingestion_proto_rawDescOnce sync.Once
	file_event_ingestion_proto_rawDescData []byte
)

func file_event_ingestion_proto_rawDescGZIP() []byte {
	file_event_ingestion_proto_rawDescOnce.Do(func() {
		file_event_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_ingestion_proto_rawDesc), len(file_event_ingestion_proto_rawDesc)))
	})
	return file_event_ingestion_proto_rawDescData
}

var file_event_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_ingestion_proto_goTypes = []any{
	(*EventRequest)(nil),          // 0: rpc_server.EventRequest
	(*IngestResponse)(nil),        // 1: rpc_server.IngestResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_event_ingestion_proto_depIdxs = []int32{
	2, // 0: rpc_server.EventRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: rpc_server.EventIngestion.CreateEvent:input_type -> rpc_server.EventRequest
	1, // 2: rpc_server.EventIngestion.CreateEvent:output_type -> rpc_server.IngestResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_ingestion_proto_init() }
func file_event_ingestion_proto_init() {
	if File_event_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_ingestion_proto_rawDesc), len(file_event_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_ingestion_proto_goTypes,
		DependencyIndexes: file_event_ingestion_proto_depIdxs,
		MessageInfos:      file_event_ingestion_proto_msgTypes,
	}.Build()
	File_event_ingestion_proto = out.File
	file_event_ingestion_proto_goTypes = nil
	file_event_ingestion_proto_depIdxs = nil
}
