// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: event_ingestion.proto

package rpcserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngestion_CreateEvent_FullMethodName = "/rpc_server.EventIngestion/CreateEvent"
)

// EventIngestionClient is the client API for EventIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventIngestionClient interface {
	CreateEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*IngestResponse, error)
}

type eventIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestionClient(cc grpc.ClientConnInterface) EventIngestionClient {
	return &eventIngestionClient{cc}
}

func (c *eventIngestionClient) CreateEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, EventIngestion_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventIngestionServer is the server API for EventIngestion service.
// All implementations must embed UnimplementedEventIngestionServer
// for forward compatibility.
type EventIngestionServer interface {
	CreateEvent(context.Context, *EventRequest) (*IngestResponse, error)
	mustEmbedUnimplementedEventIngestionServer()
}

// UnimplementedEventIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestionServer struct{}

func (UnimplementedEventIngestionServer) CreateEvent(context.Context, *EventRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventIngestionServer) mustEmbedUnimplementedEventIngestionServer() {}
func (UnimplementedEventIngestionServer) testEmbeddedByValue()                        {}

// UnsafeEventIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestionServer will
// result in compilation errors.
type UnsafeEventIngestionServer interface {
	mustEmbedUnimplementedEventIngestionServer()
}

func RegisterEventIngestionServer(s grpc.ServiceRegistrar, srv EventIngestionServer) {
	// If the following call panics, it indicates UnimplementedEventIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngestion_ServiceDesc, srv)
}

func _EventIngestion_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestion_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServer).CreateEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventIngestion_ServiceDesc is the grpc.ServiceDesc for EventIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_server.EventIngestion",
	HandlerType: (*EventIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventIngestion_CreateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event_ingestion.proto",
}
